#spring:
#  mvc:
#    static-path-pattern: /res/** #改变默认请求映射
#  web:
#    resources:
#      static-locations: # 改变静态资源存放位置，可以放多个位置，所以是一个数组配置
#        [classpath:/test/]
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

